# Generated by Django 3.2 on 2021-04-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='KANPUR', max_length=30)),
                ('status', models.CharField(choices=[('Verified', 'V'), ('Non Verified', 'NV')], max_length=20)),
                ('contactperson', models.TextField()),
                ('phone', models.BigIntegerField()),
                ('mailid', models.EmailField(blank=True, max_length=254)),
                ('bed', models.BooleanField()),
                ('oxygen', models.BooleanField()),
                ('ventilator', models.BooleanField()),
                ('tests', models.BooleanField()),
                ('fabiflu', models.BooleanField()),
                ('remdesivir', models.BooleanField()),
                ('favipiravir', models.BooleanField()),
                ('tocilizumab', models.BooleanField()),
                ('plasma', models.BooleanField()),
                ('food', models.BooleanField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
