# Generated by Django 3.2 on 2021-04-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210427_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdetails',
            name='icu',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postdetails',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
